check intel firmware
RHsyseng/openshift-checks pull request #16
Opened 2021-02-18 18:56 UTC by dcritch

This PR will list the firmware of any xxv710 Intel NICs.

2021-02-18 18:57 UTC, dcritch commented
PTAL @e-minguez  @ptrnull

2021-02-19 08:46 UTC, e-minguez commented on info/intel-firmware-version
> +# For intel xxv710 = 15b3:1015
Nit: This should be 
```suggestion
# For intel xxv710 = 8086:158a
```

2021-02-19 08:50 UTC, e-minguez commented on info/intel-firmware-version
> +# For intel xxv710 = 15b3:1015
Also, for x540-at2, the device ID is `8086:1528`

I'm not sure how shall we combine all the possible IDs...

2021-02-19 09:17 UTC, ptrnull commented on info/intel-firmware-version
> +# For intel xxv710 = 15b3:1015
We should be checking all the possibilities, right?
OpenShift Container Platform supports the following Network Interface Card (NIC) models:

    Intel XXV710 25GbE SFP28 with **vendor ID 0x8086 and device ID 0x158**
    Mellanox MT27710 Family [ConnectX-4 Lx] 25GbE dual-port SFP28 with **vendor ID 0x15b3 and device ID 0x1015**
    Mellanox MT27800 Family [ConnectX-5] 25GbE dual-port SFP28 with **vendor ID 0x15b3 and device ID 0x1017**
    Mellanox MT27800 Family [ConnectX-5] 100GbE with **vendor ID 0x15b3 and device ID 0x1017**
    Mellanox MT27700 Family [ConnectX-4] VPI adapter card, EDR IB (100Gb/s), single-port QSFP28 with **vendor ID 0x15b3 and device ID 0x1013**
    Mellanox MT27800 Family [ConnectX-5] VPI adapter card, EDR IB (100Gb/s), single-port QSFP28 with **vendor ID 0x15b3 and device ID 0x1017**
    Mellanox MT28908 Family [ConnectX-6] VPI adapter card, 100Gb/s (HDR100, EDR IB), single-port QSFP56 with **vendor ID 0x15b3 and device ID 0x101b**
    Mellanox MT28908 Family [ConnectX-6] VPI adapter card, HDR200 IB (200Gb/s), single-port QSFP56 with vendor ID **0x15b3 and device ID 0x101b**

[supported-devices_about-sriov](https://docs.openshift.com/container-platform/4.6/networking/hardware_networks/about-sriov.html#supported-devices_about-sriov)

Upstream doc looks not updated (I'll submit them a PR):
https://github.com/openshift/sriov-network-operator/blob/master/doc/quickstart.md#prerequisites

But code never lies:
https://github.com/openshift/sriov-network-operator/blob/68114c5fd960eb34913ce806126fd52843944a21/manifests/4.7/sriov-network-operator-sriovnetworknodepolicy.crd.yaml#L71
```
                    description: The device hex code of SR-IoV device. Allowed value
                      "0d58", "1572", "158b", "1013", "1015", "1017", "101b".
```
https://github.com/openshift/sriov-network-operator/blob/68114c5fd960eb34913ce806126fd52843944a21/manifests/4.7/sriov-network-operator-sriovnetworknodepolicy.crd.yaml#L89
```
                    description: The vendor hex code of SR-IoV device. Allowed value
                      "8086", "15b3".
```

2021-02-19 10:16 UTC, e-minguez commented on info/intel-firmware-version
> +# For intel xxv710 = 15b3:1015
Ok, so this works:

```
IDS="8086:1528 8086:158a"

if oc auth can-i debug node > /dev/null 2>&1; then
  msg "Checking Intel firmware version (${BLUE}using oc debug, it can take a while${NOCOLOR})"
  for node in $(oc get nodes -o name); do
    FIRMWAREVERS=$(oc debug "${node}" -- chroot /host sh -c "for id in "${IDS}"; do for device in \$(lspci -D -d "\${id}" | awk '{ print \$1 }'); do echo -n \"\${device} => \"; lspci -vv -D -s "\${device}" | egrep \"\[V0\]\" | awk '{print \$NF}' ;done;done" 2> /dev/null)
```

Now I guess the best option would be to:
* Add those changes to the mellanox script to support multiple IDS (I'll send the PR)
* Modify this one to allow future nics

2021-02-19 10:17 UTC, e-minguez requested changes
I miss the entry in the README file for the script :)
Also a comment to make the script 'future proof' just in case there are more intel nics supported in the future (see the conversation)

2021-02-19 14:06 UTC, dcritch commented
okay, made the changes. somehow my alert commit is still in there. it should merge fine.

wondering can you us lspci for Mellanox as well, rather than the vpd thing? maybe we can have one nic-firmware-version check to rule em all

2021-02-19 14:31 UTC, e-minguez commented
> okay, made the changes. somehow my alert commit is still in there. it should merge fine.
> 
> wondering can you us lspci for Mellanox as well, rather than the vpd thing? maybe we can have one nic-firmware-version check to rule em all

Mellanox firmware version seems to be in lspci output but in [VB]:

```
	Capabilities: [48] Vital Product Data
			[PN] Part number: xx
			[EC] Engineering changes: A04
			[MN] Manufacture ID: 1028
			[SN] Serial number: xx
			[VA] Vendor specific: xx
			[VB] Vendor specific: FFV14.26.60.00
```

This works tho...

```
lspci -vv -D -s 19:00.0 | egrep "\[V0\]|\[VB\]" | awk '{print $NF}'
FFV14.26.60.00
```

So maybe merging the two scripts (I propose 'sriov-nics-firmware' as name) and tweaking the egrep to include V0 or VB....

2021-02-19 14:34 UTC, ptrnull commented
I'll let them in separate pieces, easy to maintain and an issue in one of them doesn't affect the other. KISS

2021-02-19 14:51 UTC, dcritch commented
I also vote for separate pieces, but maybe its time to talk shared functions?

2021-02-19 14:51 UTC, dcritch commented
well, add some more things to utils

2021-02-19 15:30 UTC, e-minguez commented on info/intel-firmware-version
> +IDS="8086:1528 8086:158a"
If we are going to add only supported nics, then I guess we can get rid of 8086:1528 and use 8086:158a only.
```suggestion
IDS="8086:158a"
```

2021-02-19 15:31 UTC, e-minguez commented
> I also vote for separate pieces, but maybe its time to talk shared functions?

👍🏻 

WRT this PR, I've added a new comment.

2021-02-19 15:50 UTC, dcritch commented
okay, I removed the other ID, but left the loop for the future :rocket:

2021-02-19 16:08 UTC, merged