Changes required for Cronjob
RHsyseng/openshift-checks pull request #34
Opened 2021-03-01 20:15 UTC by dcritch

1/ Use the ose-cli container for the base (already worked out oc login logic)
2/ add explicit command so we can ` || exit 0` when an issue is found, without causing a bunch of pod restarts
3/ change the KUBECONFIG test. (no current-context in ose-cli)

Fixes #33

2021-03-02 07:39 UTC, e-minguez requested changes

2021-03-02 07:39 UTC, e-minguez commented on cronjob.yaml
> +            command: [
What about modifying the settings for the cronjob object so if it fails, it isn't restarted but marked as failed instead? Something like https://stackoverflow.com/a/51687712

2021-03-02 18:09 UTC, dcritch commented on cronjob.yaml
> +            command: [
Okay, I made some changes and it looks good now, though I left the command bit in there since I like explicitly knowing what's going on. WDYT?

2021-03-03 08:47 UTC, e-minguez approved these changes

2021-03-03 08:47 UTC, merged