Added precheck for required DNS
RHsyseng/openshift-checks pull request #58
Opened 2021-04-19 12:51 UTC by e-minguez

2021-04-19 20:17 UTC, dcritch requested changes

2021-04-19 20:17 UTC, dcritch commented on pre/dns-hostnames
> +    if [ ${IP_WILDCARD_REVERSE} != ${WILDCARD} ]; then
I don't think you can count on the wildcard IP's reverse to point to foobar. e.g. in one of my IT managed clusters, its wildcard.apps.... while in our lab, the reverse isn't usually resolvable at all.

2021-04-19 20:17 UTC, dcritch commented on pre/dns-hostnames
> +      msg "${API} doesn't match the reverse ${IP_API_REVERSE}"
should be wildcard doesn't match, not API

2021-04-20 06:51 UTC, e-minguez commented on pre/dns-hostnames
> +    if [ ${IP_WILDCARD_REVERSE} != ${WILDCARD} ]; then
You are right, I commented out the wildcard reverse.

2021-04-20 06:51 UTC, e-minguez commented on pre/dns-hostnames
> +      msg "${API} doesn't match the reverse ${IP_API_REVERSE}"
You are right, I fixed it but it is already commented out.

2021-04-20 06:52 UTC, e-minguez commented
I've made the errors red and the 'warnings' yellow for this check as well.

2021-04-20 17:44 UTC, dcritch commented
thanks!

2021-04-20 17:44 UTC, merged