Adding SSH check for hung kubelet/excessive authentication-operator consumption
RHsyseng/openshift-checks pull request #67
Opened 2021-05-04 23:24 UTC by dcritch

This change introduces SSH based checks, with the first one checking for high memory usage of the authentication-operator, which can be an indicator of a hung kubelet.

2021-05-05 09:01 UTC, iranzo requested changes
I've some other comments regarding of the 'ssh' checks, I'll comment at issue #30 as this might be related

2021-05-05 09:01 UTC, iranzo commented on ssh/bz1941840
> +      if [ -n "${AUTH_OPERATOR_MEMORY}" ] && [ "${AUTH_OPERATOR_MEMORY}" -gt 2147483648 ]; then # more than 2GB is a bad sign
ssh/bz1941840: line 12: [: null: integer expression expected

In my execution test, the output of AUTH_OPERATOR_MEMORY was set to 'null', failing the comparison there

`[kni@rna1-worker-0 openshift-checks]$ ssh -q core@$node 'sudo crictl stats --id $(sudo crictl ps --name authentication-operator -o json | jq -r .containers[0].id) -o json| jq -r .stats[0].memory.workingSetBytes.value'
null`

2021-05-05 09:49 UTC, iranzo commented on ssh/bz1941840
> +
Add on line 2 or 3:

# bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1948052

2021-05-05 09:56 UTC, iranzo commented on README.md
> +| [bz1941840](ssh/bz1941840)                            | Checks if the authentication-operator is using excessive RAM -> hung kubelet [BZ1941840](https://bugzilla.redhat.com/show_bug.cgi?id=1948052)
I would also suggest to move the 'description' to each test, and generate the output automatically from the execution wrapper (but that's for another PR)

2021-05-05 13:49 UTC, dcritch commented on ssh/bz1941840
> +
Done!

2021-05-05 13:50 UTC, dcritch commented on ssh/bz1941840
> +      if [ -n "${AUTH_OPERATOR_MEMORY}" ] && [ "${AUTH_OPERATOR_MEMORY}" -gt 2147483648 ]; then # more than 2GB is a bad sign
Thanks... I popped on that cluster and it was 4.4.5. Looks like back then, the name wasn't as clear. But I got the actual cri-o ID and that seems to work better. Can you check now?

2021-05-05 13:58 UTC, iranzo commented on ssh/bz1941840
> +      if [ -n "${AUTH_OPERATOR_MEMORY}" ] && [ "${AUTH_OPERATOR_MEMORY}" -gt 2147483648 ]; then # more than 2GB is a bad sign
It works fine on the test cluster now :)

2021-05-05 13:59 UTC, iranzo approved these changes
/lgtm

2021-05-06 08:11 UTC, ptrnull approved these changes
Looks good to me.
```
./openshift-checks.sh -s ssh/bz1941840 
Using kube:admin context
Checking for a hung kubelet...
Running ssh-based health checks as kube:admin
Checking for a hung kubelet...
No issues found
```

2021-05-06 13:30 UTC, merged