adding info script for locks
RHsyseng/openshift-checks pull request #82
Opened 2021-12-03 17:40 UTC by dcritch

Adding a script to list out all `namespace/pods` with locks.

2021-12-07 13:36 UTC, patrickeasters reviewed
Looks good! Just a question and a nitpick.

2021-12-07 13:36 UTC, patrickeasters commented on info/locks
> +SCRIPT=IyEvdXNyL2Jpbi9lbnYgYmFzaAoKZGVjbGFyZSAtQSBuc19wb2RzCk9SSUdfSUZTPSRJRlMKSUZTPSQoZWNobyAtZW4gIlxuXGIiKQoKZm9yIGxpbmUgaW4gJChzdWRvIGxzbG9ja3MgfCBlZ3JlcCAtdiAnKHVua25vd24pJyB8IGF3ayAne3ByaW50ICQy
For the sake of readability, could we include the script non-encoded here? Something like this should behave the same, but also be clearer for review/version control/etc:
```bash
SCRIPT=$(cat <<'EOF' | base64 -w 0
#!/usr/bin/env bash

declare -A ns_pods
ORIG_IFS=$IFS
IFS=$(echo -en "\n\b")

for line in $(sudo lslocks | egrep -v '(unknown)' | awk '{print $2}' | sort -nr | uniq -c | sort -nr | egrep -v 'unknown|-1' | grep -v PID); do
  count=$(echo $line | awk '{print $1}');
  pid=$(echo $line | awk '{print $2}');
  orig_pid=$pid
  ppid=$(grep PPid /proc/${pid}/status | awk '{print $2}')
  while [[ $ppid -gt 1 ]]; do
    pid=$ppid
    ppid=$(grep PPid /proc/${pid}/status | awk '{print $2}')
  done
  if [[ $ppid -eq 1 ]]; then
    ppid=$pid
  fi
  if [[ $(ps -hp $ppid -o cmd | grep -c conmon) -eq 1 ]]; then
    ns=$(ps -hp $ppid -o cmd | grep conmon | awk '{print $9}' | awk -F/ '{print $5}' | awk -F_ '{print $1}')
    pod=$(ps -hp $ppid -o cmd | grep conmon | awk '{print $9}' | awk -F/ '{print $5}' | awk -F_ '{print $2}')
    if [ ${ns_pods["${ns}/${pod}"]} ]; then
      ns_pods["${ns}/${pod}"]=`expr ${ns_pods["${ns}/${pod}"]} + $count`
    else
      ns_pods["${ns}/${pod}"]=$count
    fi
  fi
done
for pod in "${!ns_pods[@]}"; do
  echo $pod ${ns_pods[$pod]}
done | sort -nr -k2 | column -t 

IFS=$ORIG_IFS
EOF
)
```

2021-12-07 13:36 UTC, patrickeasters commented on info/locks
> +    if ! FILE_LOCKS=$(oc debug --image="${OCDEBUGIMAGE}" "${node}" -- chroot /host sh -c "echo $SCRIPT | base64 -d > /tmp/locks.sh; chmod 755 /tmp/locks.sh; /tmp/locks.sh"); then
Should we delete this `/tmp/locks.sh` script after we're done? We've already chrooted to the host, so we'd be leaving this in the tmp directory on each node.

2021-12-07 16:51 UTC, patrickeasters approved these changes

2021-12-16 19:37 UTC, dcritch commented
@ptrnull did you want to take a look before merging this?

2021-12-16 20:32 UTC, ptrnull commented
Yes, I'll check it tomorrow.

2021-12-17 09:43 UTC, ptrnull requested changes

2021-12-17 09:43 UTC, ptrnull commented on info/locks
> +            msg "File locks found on on ${RED}${node}${NOCOLOR}"
"File locks found on **on** ${RED}${node}${NOCOLOR}"

2021-12-17 09:46 UTC, ptrnull commented
It works as expected, /lgtm

```
./openshift-checks.sh -s info/locks                                                                            [13/1844]
Using kube:admin context
Checking for locks by pod, per node (using oc debug, it can take a while)
Starting pod/rna1-master-0...
To use host binaries, run `chroot /host`

Removing debug pod ...
File locks found on on node/rna1-master-0...
f5ingress/f5-tmm-66456f9dbf-rw4wl                                   128
openshift-sriov-network-operator/sriov-network-config-daemon-bljxq  1
openshift-ovn-kubernetes/ovnkube-node-vv2c7                         1
Starting pod/rna1-master-1rna1 ...
To use host binaries, run `chroot /host`

Removing debug pod ...
File locks found on on node/rna1-master-1...
openshift-ovn-kubernetes/ovnkube-node-sc9dg  1
Starting pod/rna1-master-2rna1 ...
To use host binaries, run `chroot /host`

Removing debug pod ...
File locks found on on node/rna1-master-2...
openshift-ovn-kubernetes/ovnkube-node-hhdr9  1
Starting pod/rna1-vmaster-0-debug ...
To use host binaries, run `chroot /host`

Removing debug pod ...
File locks found on on node/rna1-vmaster-0
openshift-machine-api/metal3-b7d759489-57545   24
openshift-ovn-kubernetes/ovnkube-master-cnd6v  6
openshift-ovn-kubernetes/ovnkube-node-r5kr6    1
openshift-etcd/etcd-rna1-vmaster-0             1
Starting pod/rna1-vmaster-1-debug ...
To use host binaries, run `chroot /host`

Removing debug pod ...
File locks found on on node/rna1-vmaster-1
openshift-ovn-kubernetes/ovnkube-master-k4hzk  6
openshift-ovn-kubernetes/ovnkube-node-nr6jv    1
openshift-etcd/etcd-rna1-vmaster-1             1
Starting pod/rna1-vmaster-2-debug ...
To use host binaries, run `chroot /host`

Removing debug pod ...
File locks found on on node/rna1-vmaster-2
openshift-ovn-kubernetes/ovnkube-master-5d65f  6
openshift-ovn-kubernetes/ovnkube-node-wm7vd    1
openshift-etcd/etcd-rna1-vmaster-2             1
No issues found
```

2021-12-20 19:26 UTC, merged